networks:
    gamma:
    secretary:

services:
    secretary-db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: secretary
            POSTGRES_DB: secretary
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        networks:
            - secretary

    adminer:
        image: adminer
        restart: always
        ports:
            - 8082:8080
        networks:
            - secretary
            - gamma

    secretary-backend:
        image: styrit_secretary_manager_backend_dev
        links:
            - gotify
        depends_on:
            - secretary-db
        build:
            context: ./backend/
            dockerfile: dev.Dockerfile
        environment:
            gotify_auth_key: "123abc"
            frontend_admin_pass: "asd123"
            SECRETARY_POSTGRES_USER: secretary
            SECRETARY_POSTGRES_PASSWORD: password
            SECRETARY_POSTGRES_HOST: secretary-db
            SECRETARY_POSTGRES_DB: secretary
            SECRETARY_POSTGRES_PORT: 5432
            PYTHONUNBUFFERED: 0
            GAMMA_CLIENT_ID: client-id
            GAMMA_SECRET: secret
            GAMMA_USERINFO_URI: https://auth.chalmers.it/oauth2/userinfo
            GAMMA_TOKEN_URI: https://auth.chalmers.it/oauth2/token
            GAMMA_AUTHORIZATION_URI: https://auth.chalmers.it/oauth2/authorize
            GAMMA_REDIRECT_URI: http://localhost:3001/auth/account/callback

        ports:
            - 5000:5000
        volumes:
            - ./backend/:/usr/src/secretary-manager/backend
        networks:
            - secretary
            - gamma

    secretary-frontend:
        build:
            context: ./frontend/
            dockerfile: dev.Dockerfile
        ports:
            - 3001:3000
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - REACT_APP_DEBUG_MODE=true
        networks:
            - secretary
        extra_hosts:
            host.docker.internal: host-gateway

    gotify:
        image: cthit/gotify:latest
        environment:
            GOTIFY_PRE-SHARED-KEY: "123abc"
            GOTIFY_MOCK-MODE: "true"
            GOTIFY_DEBUG-MODE: "true"
        ports:
            - 8080:8080

    # gamma:
    #     image: ghcr.io/cthit/gamma:latest
    #     environment:
    #         DB_USER: user
    #         DB_PASSWORD: password
    #         DB_HOST: gamma-db
    #         DB_PORT: 5432
    #         DB_NAME: postgres
    # 
    #         REDIS_HOST: gamma-redis
    #         REDIS_PASSWORD: ""
    #         REDIS_PORT: 6379
    # 
    #         GOTIFY_KEY: "123abc"
    #         GOTIFY_BASE_URL: http://gotify:8080
    # 
    #         BASE_URL: "http://localhost:8081"
    #         SERVER_PORT: 8081
    #         PRODUCTION: "false"
    #         IS_MOCKING: "false"
    #         ADMIN_SETUP: "true"
    #     depends_on:
    #         - gamma-redis
    #         - gamma-db
    #     networks:
    #         - gamma
    #     ports:
    #         - 8081:8081
    # 
    # gamma-redis:
    #     image: redis:5.0
    #     networks:
    #         - gamma
    # 
    # gamma-db:
    #     image: postgres:10
    #     environment:
    #         POSTGRES_USER: user
    #         POSTGRES_DB: postgres
    #         POSTGRES_PASSWORD: password
    #     networks:
    #         - gamma
